
target 'bsbdj-zph' do
   pod 'AFNetworking', '~> 3.1.0'
   pod 'MJExtension', '~> 3.0.13'
    pod 'SDWebImage', '~> 3.8.2'
   pod 'SVProgressHUD', '~> 2.0.4'
   pod 'DACircularProgress', '~> 2.3.1'
   pod 'MJRefresh', '~> 3.1.12'
end
